version: '3,8'

services:
  db:
    image: postgres:15
    container_name: my_app
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=oficina_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Postgres123!
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: